### PR TITLE
detectAvroVersion(): fixes 1.11.1 version handling

### LINKED ISSUE #385: Avro 1.11.1 incorrectly detected as 1.10
Looks like the version detection looking for 'record' in the list of RESERVED_WORDS in org.apache.avro.specific.SpecificData was changed in 1.11.1: https://issues.apache.org/jira/browse/AVRO-3305

### PR DESCRIPTION
**Pull request by dg-builder**
Fixes #385.

Tested locally against Avro 1.11.1

### CODE REVIEW

File: helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java [hunk 1]
```diff
@@ -856,14 +856,37 @@ private static AvroVersion detectAvroVersion() {
       return AvroVersion.AVRO_1_9;
     }
 
+    // DataFileReader(SeekableInput sin, DatumReader<D> reader, boolean closeOnError, byte[] magic)
+    // was introduced in 1.11.1 https://issues.apache.org/jira/browse/AVRO-3482
+    boolean dataFileReaderClassContains1_11Constructor = false;
```
Comment (li-ukumar) [inline helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java:861]: Add a unit test similar to `AvroCompatibilityHelperAvro111Test` for 1.11.1

File: helper/tests/helper-tests-111/build.gradle [hunk 2]
```diff
@@ -39,8 +39,8 @@ dependencies {
     exclude group: "org.apache.avro"
   }
 
-  testImplementation "org.apache.avro:avro:1.11.0"
+  testImplementation "org.apache.avro:avro:1.11.1"
   testImplementation "org.apache.avro:avro-compiler:1.11.0"
```
Comment (li-ukumar) [inline helper/tests/helper-tests-111/build.gradle:43]: compiler still 1.11.0?
