### PR TITLE
[helper] Set the field default sort order to ASCENDING.

### LINKED ISSUE #268: [helper] FieldBuilder causes NPE when order is not supplied for a field
I have some code that looks like:
```
AvroCompatibilityHelper.newField(null)
  .setName("foo")
  .setSchema(...)
  .build()
```

This throws the following exception:
```
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.apache.avro.Schema$Field.<init>(Schema.java:597)
	at com.linkedin.avroutil1.compatibility.avro110.FieldBuilder110.build(FieldBuilder110.java:101)
```

The line in question from `Schema$Field` is the `Objects.requireNonNull` line below:
```java
    public Field(String name, Schema schema, String doc, Object defaultValue, Order order) {
      this(name, schema, doc,
          defaultValue == NULL_DEFAULT_VALUE ? NullNode.getInstance() : JacksonUtils.toJsonNode(defaultValue), true,
          Objects.requireNonNull(order));
    }
```
The issue appears to come from this line in `FieldBuilder110`:
```java
    Schema.Field result = new Schema.Field(_name, _schema, _doc, avroFriendlyDefault, _order);
```
Overloads exist for `new Schema.Field` which do not require the order to be specified, and it defaults to `Order.ASCENDING`. I would expect the builder to behave similarly, by not requiring order and just defaulting to `Order.ASCENDING` if the user did not supply it.

This is on Avro 1.10, I am not sure if it applies to other Avro versions as well.

### PR DESCRIPTION
**Pull request by srramach**
Fixes #268.

### CODE REVIEW

File: helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java [hunk 1]
```diff
@@ -98,7 +98,7 @@ public FieldBuilder copyFromField() {
     } catch (Exception e) {
       throw new IllegalArgumentException("unable to convert default value " + _defaultVal + " into something avro can handle", e);
     }
-    Schema.Field result = new Schema.Field(_name, _schema, _doc, avroFriendlyDefault, _order);
+    Schema.Field result = new Schema.Field(_name, _schema, _doc, avroFriendlyDefault, _order == null ? Order.ASCENDING : _order);
```
Comment (radai-rosenblatt) [inline helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java:101]: nit - if we initialize the _order field to ASCENDING in the parent class it would save us having to do this in all the subclasses ?

Comment (radai-rosenblatt) [reply helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java:101]: (we would need to add an assert that _order != null at this point though)

Comment (radai-rosenblatt) [reply helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java:101]: ...which maybe we can also do in the parent class by introducing some validate() method called 1st thing on build()

Comment (srramach) [reply helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java:101]: I wanted to do it this way so that even if somebody explicitly calls `setOrder(null)`, we'll correctly transform it into ASCENDING.

File: helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/FieldBuilderTest.java [hunk 2]
```diff
@@ -67,6 +67,39 @@ public void testDefaultValuesInterop() throws Exception {
...
+        }
+    }
+
+    @Test
+    public void testNewFieldSortOrder() throws Exception {
+        // default (no order specified).
+        Schema.Field field = AvroCompatibilityHelper.newField(null).setName("default").build();
+        Assert.assertEquals(field.order(), Schema.Field.Order.ASCENDING);
+
+        // explicit set the order to null (in our API); should get transformed to ASCENDING.
```
Comment (radai-rosenblatt) [inline helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/FieldBuilderTest.java:86]: should result in IllegalArgumentException out of build(). likely users who set to null are doing something wrong?

File: helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java (hunk 1 above)
Comment (srramach) [reply helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java:101]: Also, there's no "parent class". Each of the FieldBuilderXX implements an interface, and don't extend some parent class.

Comment (srramach) [reply helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java]: Changed the code. PTAL.

File: helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/FieldBuilderTest.java (hunk 2 above)
Comment (srramach) [reply helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/FieldBuilderTest.java]: Done, but doing it in setOrder(), as discussed offline.

**Review by radai-rosenblatt — APPROVED** [review]
